# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名')),
                ('zh_name', models.CharField(max_length=100, verbose_name='角色中文名')),
                ('desc', models.CharField(blank=True, max_length=500, verbose_name='角色权限说明')),
                ('flag', models.IntegerField(default=0, verbose_name='标志')),
                ('creator', models.CharField(blank=True, max_length=30, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
