# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('creator', models.CharField(max_length=30, verbose_name='创建人')),
                ('work_order_id', models.IntegerField(verbose_name='工单id')),
                ('flow', models.CharField(blank=True, max_length=10, verbose_name='流程')),
                ('data', models.CharField(max_length=999, verbose_name='表单提交数据')),
                ('state', models.IntegerField(default=1, verbose_name='当前状态')),
                ('cur_role_id', models.IntegerField(verbose_name='当前处理角色id')),
                ('cur_users', models.CharField(blank=True, max_length=999, verbose_name='当前可处理人列表')),
                ('cur_user', models.CharField(blank=True, max_length=30, verbose_name='当前处理人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Task_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(verbose_name='任务id')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('role_id', models.IntegerField(verbose_name='角色id')),
                ('act_type', models.IntegerField(default=1, verbose_name='处理类型')),
                ('act_opinion', models.TextField(blank=True, max_length=1000, verbose_name='处理意见反馈')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Work_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='工单名(英文)')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('desc', models.TextField(blank=True, verbose_name='描述')),
                ('flow', models.CharField(blank=True, max_length=10, verbose_name='流程')),
                ('take_time', models.IntegerField(blank=True, default=1, verbose_name='操作需要时间')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否启动')),
                ('creator', models.CharField(max_length=30, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
